### ISSUE TITLE
A sample project would be great.

### ISSUE THREAD

**Issue by peleteiro** [moxystudio/webpack-isomorphic-dev-middleware#61]
I'm trying to use webpack-isomorphic-dev-middleware and I miss having a sample project.

**Comment by andregoncalvesdev** [comment]
Hey @peleteiro ! Check our [boilerplate](https://github.com/moxystudio/react-with-moxy/blob/7e3a8f186c02b7c89b37642a3541606ffcfdbd3c/scripts/start-dev.js#L113)

**Comment by peleteiro** [comment]
Thanks!
